# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://tyler-korenyi-both.github.io/mfsm2/"

git_url = "https://github.com/tyler-korenyi-both/mfsm2/tree/master/"

def custom_doc_links(name): return None
